package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.DotnetBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        dotnetBuild {
            name = "dotnet"
            id = "dotnet"
        }
        dotnetBuild {
            name = "dotnet"
            id = "dotnet2"
        }
        script {
            name = "Progress"
            id = "Progress"
            scriptContent = "echo"
        }
    }
    steps {
        update<DotnetBuildStep>(0) {
            name = "dotnet2"
            clearConditions()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
